id: P004466
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 11:24:06.129618
source_metadata:
  id: bdr:W8LS18496
  title: རྫ་ཡུལ་གྱི་ཡུལ་སྲོལ་རིག་གནས་ཀུན་འདུས་ཤེལ་དཀར་བུམ་པ།
  author: ''
  volumes:
    7b4ca8d309654cc0acae482af9093fdc:
      image_group_id: I8LS18498
      title: ''
      volume_number: 1
      total_pages: 533
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
