id: P004466
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18496
  title: རྫ་ཡུལ་གྱི་ཡུལ་སྲོལ་རིག་གནས་ཀུན་འདུས་ཤེལ་དཀར་བུམ་པ།
  author: ''
  volumes:
    7b4ca8d309654cc0acae482af9093fdc:
      image_group_id: I8LS18498
      title: ''
      volume_number: 1
      total_pages: 533
