id: IC9DA18D7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:20:18+00:00'
last_modified: '2022-06-08T01:17:09.743909+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18496
  title: རྫ་ཡུལ་གྱི་ཡུལ་སྲོལ་རིག་གནས་ཀུན་འདུས་ཤེལ་དཀར་བུམ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    408C:
      image_group_id: I8LS18498
      title: ''
      total_pages: 533
      order: 1
      base_file: 408C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
